### ISSUE TITLE
New files are ignored

### ISSUE THREAD

**Issue by miha-plesko** [doits/pronto-eslint_npm#14]
Thanks for this great plugin! One thing, though, I'm using the command like this (to only see issues introduced by my last commit):

```
bundle exec pronto run --runner eslint_npm -c=upstream/master
```

Now, if I add a new .jsx file (which doesn't exist in upstream/master yet) then the eslint will just ignore it - even if there is linting issue it won't report it. So I need to manually verify every new file with

```
yarn exec eslint /path/to/file
```

**Comment by doits** [comment]
Please see https://github.com/ngudbhav/pronto-npm-eslint for a maintained fork of this gem and open an issue there if the issue is still happening. Thank!
