### ISSUE TITLE
Compatibility with pronto 0.11

### ISSUE THREAD

**Issue by Vasfed** [doits/pronto-eslint_npm#17]
Current gemspec locks pronto at `~> 0.10.0`, most likely everything should work with a more relaxed `~>0.10`.
Pronto's [changelog](https://github.com/prontolabs/pronto/blob/master/CHANGELOG.md) for 0.11 has no breaking changes.

**Comment by hlascelles** [comment]
We'd like this too... However this gem appears unmaintained: "This gem is not maintained anymore and will receive no updates. If you want to step in as a maintainer, please open an issue to discuss it." We may switch back to using the non-fork, or maybe offer to take this over. Not sure yet.

**Comment by hlascelles** [comment]
Looking at the network graph at least 8 people have forked this and are running from a branch with patches to support pronto 0.11. A simple gem release with the new version would be well received, if even with no other changes.

**Comment by ArchieJG** [comment]
I have made a PR to fix this #19

**Comment by doits** [comment]
New version 0.11.0 is released which should run with pronto 0.11.

**Comment by hlascelles** [comment]
:bow: Thank you! :fireworks:
