### ISSUE TITLE
Specify javascripts path

### ISSUE THREAD

**Issue by KODerFunk** [doits/pronto-eslint_npm#5]
Need option for specify javascripts path(s)
In my project, client-side app filed placed in `./client` and eslint do work very slow, because scan all directories in my rails-app (`.`).

**Comment by doits** [comment]
Please see [files_to_lint option](https://github.com/doits/pronto-eslint_npm#configuration-of-eslintnpm). In you case something like `/client/.*\.js$` should work?

**Comment by doits** [comment]
Oh and you can use an `.eslintignore`, too: http://eslint.org/docs/user-guide/configuring#ignoring-files-and-directories

Please reopen if you still need more options for your use case.

**Comment by KODerFunk** [comment]
@doits i make it, because it sole solution. `.eslintignore` with `!client/*` exists but ignored when run pronto :(

**Comment by doits** [comment]
You want to exclude everything but `client/`? Try this `.eslintignore`:

```
# first ignore everything (maybe `*` would be enough) ...
**/*

# ... and explicitly include `client/`
!client/**
```
